"""Loads the knowledge dossier generated by career-ops' export-dossier.mjs.

Never edit data/*.json or data/*.txt by hand — they're a build artifact.
Regenerate from career-ops and re-run scripts/sync-dossier.sh (see ../../README.md).
"""

import json
from functools import lru_cache
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"


@lru_cache
def load_facts() -> dict:
    path = DATA_DIR / "facts.json"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} is missing. Run scripts/sync-dossier.sh <path-to-career-ops> first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


@lru_cache
def load_summary() -> str:
    return (DATA_DIR / "summary.txt").read_text(encoding="utf-8").strip()


@lru_cache
def load_style() -> str:
    return (DATA_DIR / "style.txt").read_text(encoding="utf-8").strip()


@lru_cache
def load_dossier_text() -> str:
    """The full markdown dossier — same shape used by worker/src/knowledge.ts."""
    return (DATA_DIR / "dossier.md").read_text(encoding="utf-8").strip()
